server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: checkIn
          uri: http://localhost:8081
          predicates:
            - Path=/checkIns/** 
        - id: point
          uri: http://localhost:8082
          predicates:
            - Path=/deducts/**,/earns/**,/prohibits/**
        - id: pay
          uri: http://localhost:8083
          predicates:
            - Path=/pays/** 
        - id: customercenter
          uri: http://localhost:8084
          predicates:
            - Path= /mypages/**
        - id: penalty
          uri: http://localhost:8085
          predicates:
            - Path=/penalties/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: checkIn
          uri: http://skccuer21-checkIn:8080
          predicates:
            - Path=/checkIns/** 
        - id: point
          uri: http://skccuer21-point:8080
          predicates:
            - Path=/deducts/**,/earns/**,/prohibits/**
        - id: pay
          uri: http://skccuer21-pay:8080
          predicates:
            - Path=/pays/** 
        - id: customercenter
          uri: http://skccuer21-customercenter:8080
          predicates:
            - Path= /mypages/**
        - id: penalty
          uri: http://skccuer21-penalty:8080
          predicates:
            - Path=/penalties/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
